api_platform:
    title: 'HB Toys'
    description: 'HB Toys site de vente de jouets'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
